epde_params = {
    'burgers_sln_100_data.csv': {
        'population_size': 16,
        'training_epochs': 5,
        'use_solver': False,
        'use_pic': True,
        'boundary': (10, 10),
        'default_preprocessor_type': 'poly',
        'variable_names': ['u', ],
        'max_deriv_order': (2, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 3,
        'additional_tokens': None,
        'equation_factors_max_number': {'factors_num': [1, 2], 'probas': [0.8, 0.2]},
        'eq_sparsity_interval': (1e-6, 1e-0),
        'fourier_layers': True
    },
    
    'ac_data.npy': {
        'population_size': 8,
        'training_epochs': 30,
        'use_solver': False,
        'multiobjective_mode': True,
        'use_pic': True,
        'boundary': 20,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u', ],
        'max_deriv_order': (2, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 3,
        'additional_tokens': None,
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-5, 1e-2),
        'fourier_layers': False
    },

    'kdv_data.mat': {
        'population_size': 8,
        'training_epochs': 15,
        'use_solver': False,
        'use_pic': True,
        'boundary': 10,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u', ],
        'max_deriv_order': (1, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 1,
        'additional_tokens': None,
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-5, 1e-2),
        'fourier_layers': False
    },

    'burgers_data.mat': {
        'population_size': 8,
        'training_epochs': 15,
        'use_solver': False,
        'multiobjective_mode': True,
        'use_pic': True,
        'boundary': 20,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u', ],
        'max_deriv_order': (2, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 3,
        'additional_tokens': None,
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-4, 1e-0),
        'fourier_layers': False
    },

    'ks_data.mat': {
        'population_size': 16,
        'training_epochs': 10,
        'use_solver': False,
        'multiobjective_mode': True,
        'use_pic': True,
        'boundary': 5,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u'],
        'max_deriv_order': (1, 4),
        'equation_terms_max_number': 10,
        'data_fun_pow': 1,
        'additional_tokens': None,
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-12, 1e-0),
        'fourier_layers': False
    },

    'pde_divide_data.npy': {
        'population_size': 8,
        'training_epochs': 50,
        'use_solver': False,
        'use_pic': True,
        'boundary': 20,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u'],
        'max_deriv_order': (2, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 1,
        'additional_tokens': 'CacheStoredTokens',
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-9, 1e-2),
        'fourier_layers': False
    },

    'pde_compound_data.npy': {
        'population_size': 8,
        'training_epochs': 50,
        'use_solver': False,
        'use_pic': True,
        'boundary': 20,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u'],
        'max_deriv_order': (2, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 1,
        'additional_tokens': 'CacheStoredTokens',
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-9, 1e-2),
        'fourier_layers': False
    },

    'lorenz_data.npy': {
        'population_size': 8,
        'training_epochs': 2,
        'use_solver': False,
        'use_pic': True,
        'boundary': 10,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u', 'v', 'w'],
        'max_deriv_order': (1,),
        'equation_terms_max_number': 5,
        'data_fun_pow': 1,
        'additional_tokens': 'TrigonometricTokens',
        'equation_factors_max_number': {'factors_num': [1, 2], 'probas' : [0.8, 0.2]},
        'eq_sparsity_interval': (1e-4, 1e-0),
        'fourier_layers': False,
        'coordinate_tensors': '1d',
        'trig_tokens_freq': (2 - 1e-8, 2 + 1e-8)
    },

    'lotka_data.npy': {
        'population_size': 8,
        'training_epochs': 1,
        'use_solver': False,
        'use_pic': True,
        'boundary': 10,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u', 'v'],
        'max_deriv_order': (1,),
        'equation_terms_max_number': 5,
        'data_fun_pow': 1,
        'additional_tokens': 'TrigonometricTokens',
        'equation_factors_max_number': {'factors_num': [1, 2], 'probas' : [0.8, 0.2]},
        'eq_sparsity_interval': (1e-4, 1e-0),
        'fourier_layers': False,
        'coordinate_tensors': '1d',
        'trig_tokens_freq': (2 - 1e-8, 2 + 1e-8)
    },

    'ode_data.npy': {
        'population_size': 8,
        'training_epochs': 15,
        'use_solver': False,
        'use_pic': True,
        'boundary': 10,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u'],
        'max_deriv_order': (2, 2),
        'equation_terms_max_number': 5,
        'data_fun_pow': 1,
        'additional_tokens': 'TrigonometricTokens, GridTokens',
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-12, 1e-4),
        'fourier_layers': False,
        'coordinate_tensors': '1d',
        'trig_tokens_freq': (2 - 1e-8, 2 + 1e-8)
    },

    'kdv_periodic_data.npy': {
        'population_size': 12,
        'training_epochs': 15,
        'use_solver': False,
        'use_pic': True,
        'boundary': 10,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u'],
        'max_deriv_order': (1, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 1,
        'additional_tokens': 'custom_trig_tokens',
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-10, 1e-2),
        'fourier_layers': False
    },

    'vdp_data.npy': {
        'population_size': 8,
        'training_epochs': 15,
        'use_solver': False,
        'use_pic': True,
        'boundary': 10,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u'],
        'max_deriv_order': (2, 2),
        'equation_terms_max_number': 5,
        'data_fun_pow': 2,
        'additional_tokens': 'TrigonometricTokens, GridTokens',
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-8, 1e-0),
        'fourier_layers': False,
        'coordinate_tensors': '1d',
        'trig_tokens_freq': (2 - 1e-8, 2 + 1e-8)
    },

    'wave_data.csv': {
        'population_size': 8,
        'training_epochs': 5,
        'use_solver': False,
        'use_pic': True,
        'boundary': 20,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u'],
        'max_deriv_order': (2, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 3,
        'additional_tokens': None,
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-12, 1e-2),
        'fourier_layers': False,
        'coordinate_tensors': 'wave_data'
    },

    'ns_data.mat': {
        'population_size': 16,
        'training_epochs': 50,
        'use_solver': False,
        'multiobjective_mode': True,
        'use_pic': True,
        'boundary': 5,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u', 'v', 'p'],
        'max_deriv_order': (1, 2, 2),
        'equation_terms_max_number': 10,
        'data_fun_pow': 1,
        'additional_tokens': None,
        'equation_factors_max_number': {'factors_num': [1, 2], 'probas': [0.8, 0.2]},
        'eq_sparsity_interval': (1e-12, 1e-0),
        'fourier_layers': False,
        'coordinate_tensors': '3d'
    },

    'ODE_simple_discovery': {
        'population_size': 8,
        'training_epochs': 20,
        'use_solver': False,
        'use_pic': True,
        'boundary': 10,
        'default_preprocessor_type': 'FD',
        'variable_names': ['u'],
        'max_deriv_order': (2, 3),
        'equation_terms_max_number': 5,
        'data_fun_pow': 3,
        'additional_tokens': 'ODE_simple_discovery',
        'equation_factors_max_number': {"factors_num": [1, 2], "probas": [0.65, 0.35]},
        'eq_sparsity_interval': (1e-4, 1e-0),
        'fourier_layers': False,
        'coordinate_tensors': '1d',
        'trig_tokens_freq': (0.999, 1.001)
    },
}